AmbulanceSystem/src/AmbulanceSystem/ViewModels/CreateIpsViewModel.cs
using AmbulanceSystem.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmbulanceSystem.ViewModels
{
    public class CreateIpsViewModel
    {        
        [Required, MaxLength(40),Display(Name="IPS Name")]
        public string Name { get; set; }
        [Required, Display(Name = "IPS Type")]
        public string Type { get; set; }
        [Display(Name="Direction of the IPS")]
        public Direction Direction { get; set; }
    }
}

AmbulanceSystem/src/AmbulanceSystem/Controllers/AmbulanceController.cs
using AmbulanceSystem.Entities;
using AmbulanceSystem.ViewModels;
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmbulanceSystem.Controllers
{
    public class AmbulanceController : Controller
    {
        private IServicesAmbulance _servicesAmbulance;

        public AmbulanceController(IServicesAmbulance servicesAmbulance)
        {
            this._servicesAmbulance = servicesAmbulance;
        }

        [HttpGet]
        public IActionResult Ambulances()
        {
            var modelAmbulance = new AmbulanceViewModel();
            modelAmbulance.Ambulances = _servicesAmbulance.GetAllAmbulances();            

            return View(modelAmbulance);
        }

        [HttpGet]
        public IActionResult CreateAmbulance()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAmbulance(AmbulanceCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                Random rnd = new Random();
                var ambulance = new Ambulance();
                ambulance.AmbulanceCode = model.AmbulanceCode;
                ambulance.Plate = model.Plate;
                ambulance.ServicesList = new List<Service>();
                ambulance.State = model.AmbulanceState;
                ambulance.RoadPosition = rnd.Next(1, 200);
                ambulance.StreetPosition = rnd.Next(1, 200);
                ambulance.AmbulanceType = model.AmbulanceType;
                ambulance.TimeOfPosition = DateTime.Now;

                _servicesAmbulance.AddAmbulance(ambulance);
                _servicesAmbulance.Commit();
                return RedirectToAction("Ambulances");
            }
            return View();
        }
    }
}

AmbulanceSystem/src/AmbulanceSystem/Controllers/HomeController.cs
using AmbulanceSystem.Entities;
using AmbulanceSystem.ViewModels;
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmbulanceSystem.Controllers
{
    public class HomeController : Controller
    {
        private IServicesAmbulance _servicesAmbulance;

        public HomeController(IServicesAmbulance servicesAmbulance)
        {
            _servicesAmbulance = servicesAmbulance;
        }

        public IActionResult Index()
        {
            var model = new IndexVideModel
            {
                Ambulances = _servicesAmbulance.GetAllAmbulances(),
                Ips = _servicesAmbulance.GetAllIps(),
                Services = _servicesAmbulance.GetAllServices()
            };            

            return View(model);
        }      

        
    }
}

AmbulanceSystem/src/AmbulanceSystem/Views/Home/CreateIps.cshtml
@model AmbulanceSystem.ViewModels.CreateIpsViewModel
@{
    ViewBag.Title = "Create IPS";
}

<h1>Create IPS</h1>

<form asp-action="CreateIps" method="post">
    <div>
        <label asp-for="Name"></label>
        <div>
            <input asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>
    </div>
    <div>
        <label asp-for="Type"></label>
        <div>
            <input asp-for="Type" />
            <span asp-validation-for="Type"></span>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.Direction.Type)
        @Html.DropDownListFor(m => m.Direction, Html.GetEnumSelectList((typeof(DirectionType))))
        @Html.ValidationMessageFor(m => m.Direction.Type)
    </div>
    <div>
        @Html.LabelFor(m => m.Direction.Avenue)
        @Html.EditorFor(m => m.Direction.Avenue)
        @Html.ValidationMessageFor(m => m.Direction.Avenue)
    </div>
    <div>
        @Html.LabelFor(m => m.Direction.Street)
        @Html.EditorFor(m => m.Direction.Street)
        @Html.ValidationMessageFor(m => m.Direction.Street)
    </div>
    <div>
        @Html.LabelFor(m => m.Direction.Number)
        @Html.EditorFor(m => m.Direction.Number)
        @Html.ValidationMessageFor(m => m.Direction.Number)
    </div>
    <div>
        <input type="submit" value="Save" />
    </div>
</form>

AmbulanceSystem/src/AmbulanceSystem/Views/Home/Index.cshtml
@model AmbulanceSystem.ViewModels.IndexVideModel
@{
    ViewBag.Title = "Ambulances Company";
}

@section link {
    <link rel="stylesheet" type="text/css" href="~/lib/styles/index.css" />
}

<h1>@ViewBag.Title</h1>

    <div id="pricing" class="row">
        <div class="col-md-4">
            <div class="price_card alpha">
                <div class="header">
                    <span class="price">@Model.Ambulances.Count</span>
                    <span class="name">Ambulances</span>
                </div>
                <ul class="features">
                    <li>Click the button to see the full list</li>
                </ul>
                <a class="btn abtn" asp-controller="Ambulance" asp-action="Ambulances">Go to ambulances</a>
                <span class="tip"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="price_card bravo">
                <div class="header">
                    <span class="price">@Model.Ips.Count</span>
                    <span class="name">IPS</span>
                </div>
                <ul class="features">
                    <li>Click the button to see the full list</li>
                </ul>
                <button class="button">Go to IPS</button>
                <span class="tip"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="price_card charlie">
                <div class="header">
                    <span class="price">@Model.Services.Count</span>
                    <span class="name">Services</span>
                </div>
                <ul class="features">
                    <li>Click the button to see the full list</li>
                </ul>
                <button class="button">Go to services</button>
            </div>
        </div>        
    </div>